### ISSUE TITLE
feature/index

### ISSUE THREAD

**Issue by hmmiii** [hmmiii/mini-routine#12]
## Description

일정 조회 기능 구현을 위한 메인 페이지 구현 이슈입니다.

## Todos

- [x] 메인페이지 레이아웃 구현
- [x] db에서 일정 받아와 조회
- [x] 체크버튼으로 루틴 업데이트
- [x] 로그인 상태인지 확인
